dist: trusty
language: ruby
sudo: false
before_install:
- gem install bundler -v '1.16.2'
cache:
  yarn: true
bundler_args: "--without development production staging"
branches:
  only:
  - master
  - develop
  - feature/add-travis
rvm:
- 2.2.3
addons:
  postgresql: 9.3
before_script:
- sleep 10
- cp .env.example .env
- sudo apt-get purge libgdal1
- sudo apt-add-repository --remove ppa:ubuntugis/ppa -y
- sudo apt-get update
- sudo apt-get install libgdal1h
- sudo apt-get install gdal-bin
- sudo apt-get install libproj-dev
- sudo apt-get install libspatialite-dev --force-yes
- sudo apt-get install libgeos-c1 --force-yes
- echo libgeos-c1 hold | sudo dpkg --set-selections
- echo libgdal1 hold | sudo dpkg --set-selections
- sudo apt-get install libgdal-dev --force-yes
- sudo apt-get install libgdal1-dev --force-yes
- sudo apt-get install postgresql-9.3-postgis-2.3 -f
- psql -c 'create database blueforests_test' -U postgres
- psql -c 'CREATE EXTENSION postgis;' -U postgres -d blueforests_test
- cp config/database.yml.travis config/database.yml
- cp config/secrets.yml.travis config/secrets.yml
- git clone https://github.com/tilemill-project/tilemill vendor/tilemill
- cd vendor/tilemill
- nvm install 8.15.0
- npm install
- cd ../..
- git clone https://github.com/mapbox/projectmill.git vendor/projectmill
- cd vendor/projectmill
- npm config set registry http://registry.npmjs.org/
- nvm install 0.10.24
- npm install
- RAILS_ENV=test bundle exec rake db:create db:migrate
- RAILS_ENV=test rspec
services:
  - redis-server
notifications:
  slack:
    secure: RlKYPkZvtv2qeFCXhuwc9ph2autnObOTtvyOfL0vUEJoEm4hNiKcGEBP5q9BBRGKB9jLzh9lWeTuOgwhK9ndWnxHcIwegXoJqBTcndPhVD9gLtsvKRHqHMSiOa7sUZI/atPOJgS6cHQOkJ0msqoo31DsWzRqleimqz/++2SDsbc=