sudo: false
before_install:
  - gem install bundler -v '1.16.2'
cache:
  yarn: true
language: ruby
bundler_args: --without development production staging
branches:
  only:
  - master
  - develop
rvm:
- 2.2.3
addons:
  postgresql: 9.6
before_script:
- psql -c 'create database travis_ci_test' -U postgres
- cp config/database.yml.travis config/database.yml
- cp config/secrets.yml.travis config/secrets.yml
- git clone git@github.com:mapbox/tilemill.git vendor/tilemill
- cd vendor/tilemill
- nvm install 8.15.0
- npm install
- cd ../..
- git clone https://github.com/mapbox/projectmill.git vendor/projectmill
- cd vendor/projectmill
- npm config set registry http://registry.npmjs.org/
- nvm install 0.10.24
- npm install
- RAILS_ENV=test bundle exec rake db:migrate
notifications:
  slack: ???
