development:
  adapter: postgis
  database: blueforest_development
  pool: 25
  username: postgres
  password:
  host: localhost

test:
  adapter: postgis
  database: blueforest_test
  host: localhost
  pool: 5
  username: postgres
  password:
  host: localhost

production:
  adapter: postgresql
  database: blueforest_production
  host: localhost
