# Be sure to restart your server when you modify this file.
default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  tilemill_path: <%= Rails.root.join("vendor/tilemill") %>
  projectmill_path: <%= Rails.root.join("vendor/projectmill") %>
  mapbox_api_key: <%= ENV["MAPBOX_API_KEY"] %>

  admin_subdomain: 'admin'

  magpie_url: 'http://localhost:9000'

  cartodb:
    table_prefix: 'blueforests'
    username: 'carbon-tool'
    api_key: <%= ENV["CARTODB_API_KEY"] %>
    mapconfig:
      version: "1.0.1"
      cartocss_version: "2.0.1"

development:
  <<: *default
  secret_key_base: c9a5d44fd83941bdf5224c7ddd6da04361df0383bc45cc2e074c2b7ecc47f6730c1b5f53bd627d30182997fed6b80433c9e8040dc7f15d1bac6cbfa0a38c1dfa

test:
  <<: *default
  secret_key_base: 0f7fb46879c71772aafa694a4bdc5c821c196ab7b0b337ecf3fe994616ca2a243d4743cbfd984bb8033708c57b66cf97b5f999f11a19b8d42e72a956a7c1b770

  cartodb:
    table_prefix: 'blueforests'
    username: 'carbon-tool'
    api_key: '123456abcdef'
    mapconfig:
      version: "1.0.1"
      cartocss_version: "2.0.1"

#====================
# Production Secrets
#====================

production_defaults: &production_defaults
  <<: *default
  magpie_url: 'http://magpie.unep-wcmc.org'

# Do not keep staging secrets in the repository,
# instead read values from the environment.
staging:
  <<: *production_defaults
  base_subdomain: 'blueforests.web-staging.linode'
  magpie_url: 'http://magpie.web-staging.linode.unep-wcmc.org'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *production_defaults
